extends RefCounted

const PORTRAITS := {
	"ajian": {
		"neutral": preload("res://assets/portraits/ajian/neutral.png"),
		"happy": preload("res://assets/portraits/ajian/happy.png"),
		"angry": preload("res://assets/portraits/ajian/angry.png"),
		"blushing": preload("res://assets/portraits/ajian/blushing.png"),
		"crying": preload("res://assets/portraits/ajian/crying.png"),
		"surprised": preload("res://assets/portraits/ajian/surprised.png"),
		"tired": preload("res://assets/portraits/ajian/tired.png"),
		"smug": preload("res://assets/portraits/ajian/smug.png"),
		"terrified": preload("res://assets/portraits/ajian/terrified.png"),
	},
	"ajie": {
		"neutral": preload("res://assets/portraits/ajie/neutral.png"),
		"happy": preload("res://assets/portraits/ajie/happy.png"),
		"angry": preload("res://assets/portraits/ajie/angry.png"),
		"blushing": preload("res://assets/portraits/ajie/blushing.png"),
		"crying": preload("res://assets/portraits/ajie/crying.png"),
		"surprised": preload("res://assets/portraits/ajie/surprised.png"),
		"tired": preload("res://assets/portraits/ajie/tired.png"),
		"smug": preload("res://assets/portraits/ajie/smug.png"),
		"terrified": preload("res://assets/portraits/ajie/terrified.png"),
	},
	"buck": {
		"neutral": preload("res://assets/portraits/buck/neutral.png"),
		"happy": preload("res://assets/portraits/buck/happy.png"),
		"angry": preload("res://assets/portraits/buck/angry.png"),
		"blushing": preload("res://assets/portraits/buck/blushing.png"),
		"crying": preload("res://assets/portraits/buck/crying.png"),
		"surprised": preload("res://assets/portraits/buck/surprised.png"),
		"tired": preload("res://assets/portraits/buck/tired.png"),
		"smug": preload("res://assets/portraits/buck/smug.png"),
		"terrified": preload("res://assets/portraits/buck/terrified.png"),
	},
	"lisi": {
		"neutral": preload("res://assets/portraits/lisi/neutral.png"),
		"happy": preload("res://assets/portraits/lisi/happy.png"),
		"angry": preload("res://assets/portraits/lisi/angry.png"),
		"blushing": preload("res://assets/portraits/lisi/blushing.png"),
		"crying": preload("res://assets/portraits/lisi/crying.png"),
		"surprised": preload("res://assets/portraits/lisi/surprised.png"),
		"tired": preload("res://assets/portraits/lisi/tired.png"),
		"smug": preload("res://assets/portraits/lisi/smug.png"),
		"terrified": preload("res://assets/portraits/lisi/terrified.png"),
	},
	"miro": {
		"neutral": preload("res://assets/portraits/miro/neutral.png"),
		"happy": preload("res://assets/portraits/miro/happy.png"),
		"angry": preload("res://assets/portraits/miro/angry.png"),
		"blushing": preload("res://assets/portraits/miro/blushing.png"),
		"crying": preload("res://assets/portraits/miro/crying.png"),
		"surprised": preload("res://assets/portraits/miro/surprised.png"),
		"tired": preload("res://assets/portraits/miro/tired.png"),
		"smug": preload("res://assets/portraits/miro/smug.png"),
		"terrified": preload("res://assets/portraits/miro/terrified.png"),
	},
}
